### ISSUE TITLE
Add YouTube timestamp functionality

### ISSUE THREAD

**Issue by lauterb** [david-allison/manx-corpus-search#186]
Add a new page/route to make it easier to get timestamps for videos for proper indexing.

**Comment by david-allison** [comment]
Our use case is that we have people who have a transcript in an excel sheet and want to align speech to ~100ms so we can display it. See: <https://corpus.gaelg.im/docs/YouTube-L-Quirk-Coraaghyn-Vannin>

They need to know the `StartTime` and `EndTime` for a sentence. 

Realistically any method can work (and we CAN go for better tech), but an easy workaround is to give them a YouTube Player which shows the current time, so they can drop in a reasonable 'start' and 'end'

I would do this as a separate page (route in `React` terminology), as it's 'content creator' functionality, rather than something that a user of the corpus would need

----

Basic functionality: display current time

Optional extras: allow a user to input a start [+ end] and play the video between those two points
